apiVersion: v1
kind: Service
metadata:
  name: godot-client
spec:
  selector:
    app: godot-client   # Make sure this label matches the labels on your client pods
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 80   # Container port
