apiVersion: v1
kind: Service
metadata:
  name: godot-server
spec:
  type: NodePort
  selector:
    app: godot-server
  ports:
    - name: tcp
      protocol: TCP
      port: 8082         # internal service port
      targetPort: 8082   # container port the server is listening on
      nodePort: 31000    # external port on your node for websocket traffic
