apiVersion: v1
kind: Service
metadata:
  name: godot-client
spec:
  type: NodePort
  selector:
    app: godot-client
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 80   # Container port
      nodePort: 30000  # Exposed Port